



	<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	<script>
	$( function() {
		$( "#slider-range" ).slider({
			orientation: "vertical",
			range: true,
			min: 10,
			max: 30,
			values: [10, 30],
			slide: function( event, ui ) {
				$( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
			}
		});
		$( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
			" - $" + $( "#slider-range" ).slider( "values", 1 ) );
	} );
	</script>
	<style>
		#slider-range {
			height: 365px;
			background: #cfcfcf;
			border-radius: 15px;
			border: 1px solid #cfcfcf;
			width: 11px;
			margin-bottom: 35px;
		}
		.ui-slider-range {
			background: #ff0080;
			border: 1px solid #ff0080;
		}
		.ui-state-default, .ui-widget-content .ui-state-default {
			border-radius: 100%;
			border: 1px solid #cfcfcf;
			background: #fff;
		}
		.ui-state-default:focus, .ui-widget-content .ui-state-default:focus {
			outline: none;
		}
		a.filter-btn {
			width: 87px;
			display: inline-block;
			height: 42px;
			background: #000;
			color: #fff;
			text-align: center;
			line-height: 42px;
			font-family: 'open sans', sans-serif;
			text-decoration: none;
			font-size: 18px;
		}
		ul.ver-range-list {
			margin: 0;
			padding: 0;
			width: 45px;
			position: relative;
			left: 25px;
			list-style: none;
			text-align: center;
			height: 100%;
			display: block;
		}
		ul.ver-range-list li {
			display: block;
			margin-bottom: 17px;
		}
		ul.ver-range-list li:last-child{
			margin-bottom: 0;
		}
	</style>

<div class="filter-price-wrapper">
	<h1>Filter By Length</h1>
	<!-- p>
		<label for="amount">Target sales goal (Millions):</label>
		<input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
	</p -->
	<div id="slider-range">
		<ul class="ver-range-list">
			<li>- 10&rdquo;</li>
			<li>- 12&rdquo;</li>
			<li>- 14&rdquo;</li>
			<li>- 16&rdquo;</li>
			<li>- 18&rdquo;</li>
			<li>- 20&rdquo;</li>
			<li>- 22&rdquo;</li>
			<li>- 24&rdquo;</li>
			<li>- 26&rdquo;</li>
			<li>- 28&rdquo;</li>
			<li>- 30&rdquo;</li>
		</ul>
	</div>	
	<a href="javascript:void(0)" class="filter-btn">Filter</a>
</div><!-- filter-price-wrapper -->