
<section class="home-top-slider">
	<ul class="bxslider">
		<li>
			<img src="skin/frontend/theme9196/default/images/pic01.jpg" />
			<!-- <div class="contant">
				<h1>You’ve Found</h1>
				<h2>Your Home For</h2>
				<h3>Beyonce hair</h3>
				<h4>at Michelle prices</h4>
			</div><!-- contant -->
		</li>
		<li><img src="skin/frontend/theme9196/default/images/banner2.jpg" /></li>
		<li><img src="skin/frontend/theme9196/default/images/banner3.jpg" /></li>
	</ul>
</section><!-- home-top-slider -->

<section class="shop-with-wrapper">
	<div class="container">
		<div class="veiw-All">
			<a href="#">View All</a>
		</div>
		<div class="title-heading">
			<h1>Shop with our</h1>
			<h2>Premium Bundlenaires</h2>
			<p class="title-img">
				<img src="skin/frontend/theme9196/default/images/heading-border.png" />
			</p>
		</div><!-- title-heading -->
		<div class="owl-carousel owl-theme new-slider">
			<div class="item">
				<div class="slider-pic">
					<img src="skin/frontend/theme9196/default/images/slide01.png" alt="" title=""/>
				</div>
			</div>
			<div class="item">
				<div class="slider-pic">
					<img src="skin/frontend/theme9196/default/images/slide02.png" alt="" title=""/>
				</div>
			</div>
			<div class="item">
				<div class="slider-pic">
					<img src="skin/frontend/theme9196/default/images/slide03.png" alt="" title=""/>
				</div>
			</div>
			<div class="item">
				<div class="slider-pic">
					<img src="skin/frontend/theme9196/default/images/slide04.png" alt="" title=""/>
				</div>
			</div>
			<div class="item">
				<div class="slider-pic">
					<img src="skin/frontend/theme9196/default/images/slide05.png" alt="" title=""/>
				</div>
			</div>
			<div class="item">
				<div class="slider-pic">
					<img src="skin/frontend/theme9196/default/images/slide06.png" alt="" title=""/>
				</div>
			</div>
		</div><!-- new-slider -->
	</div><!-- container -->
</section><!-- shop-with-wrapper -->

<section class="how-does-wrapper">
	<div class="container">
		<div class="title-heading">
			<h1>How Does</h1>
			<h2>Cash Your Bundles Work?</h2>
			<p class="title-img">
				<img src="skin/frontend/theme9196/default/images/heading-border.png" />
			</p>
		</div><!-- title-heading -->
		<div class="how-does-steps ">
			<ul>
				<li>
					<span class="step-icon hair"></span>
					<span class="step-heading">Collect all your bundles</span>
					<span class="step-text">Open your hair drawer and select only your gently used and high quality virgin bundles to send in. We are highly selective so double check our quality criteria.</span>
				</li>
				<li>
					<span class="step-icon face"></span>
					<span class="step-heading">Let us make them new</span>
					<span class="step-text">We take every bundle through our sanitization and revitalization method to have them looking and feeling brand new</span>
				</li>
				<li>
					<span class="step-icon coins"></span>
					<span class="step-heading">Earn some extra coins</span>
					<span class="step-text">Bundlenaire sellers earn cash on every sold bundle and Bundlenaire buyers get beautiful hair while keeping some money in their pocket</span>
				</li>
			</ul>
		</div><!-- how-does-steps -->
	</div><!-- container -->
</section><!-- how-does-wrapper -->




<script>
	jQuery(document).ready(function() {
	  jQuery('.owl-carousel').owlCarousel({
		loop: true,
		margin: 10,
		responsiveClass: true,
		responsive: {
		  0: {
			items:2,
			nav: true
		  },
		  600: {
			items: 2,
			nav: true
		  },
		  1000: {
			items: 3,
			nav: true,
			margin: 30
		  }
		}
	  });
	});
	jQuery(document).ready(function(){
		jQuery('.bxslider').bxSlider();
	});
</script>