<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.0
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2015 Apptha. (http://www.apptha.com) Similar Bundles
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>


 
<?php 
/**
 * get seller id
 */
$getlookid = Mage::app()->getRequest()->getParam("getlook");
if(! isset($getlookid)){
$id = $this->getRequest()->getParam('id');
$currentDate = Mage::getModel('core/date')->date('Y-m-d');

/**
 * display product collection
 */
$sellerPage = Mage::getModel('marketplace/sellerprofile')->collectprofile($id);
function countget($filter, $id){
	$attribute_count_product = Mage::getModel ( 'catalog/product' )
	->getCollection()
	->addFieldToFilter( 'seller_id', $id)
	->addFieldToFilter ( 'hair_type', $filter);
	return count($attribute_count_product);
}
$collection = Mage::getModel ( 'catalog/product' )->getCollection ()->addFieldToFilter ( 'seller_id', $id);
$sellerPage = Mage::getModel('marketplace/sellerprofile')->collectprofile($id);
?>
<script>
	function filter(filterclass){
		jQuery( ".product-listing ul li" ).css( "display", "none" ).filter( '.'+filterclass ).css( "display", "block" );
	}
</script>

<div class="clear"></div>
	<div class="under-sink-wrapper">
		<div class="under-sink-container">
			<h1>Under The Sink</h1>
			<p class="title-img"><img src="http://synapse.asia/marketplace9196/skin/frontend/theme9196/default/images/heading-border.png"></p>
			<div class="listing-tabber">
				<ul>
					<li><a href="javascript:filter('Straight')"><img src="<?php echo $this->getSkinUrl('images/straight.png')?>" >Straight <span class="num">(<?php echo countget(22, $id); ?>)</span></a></li>
					<li><a href="javascript:filter('Wavy')"><img src="<?php echo $this->getSkinUrl('images/wavy.png')?>" >Wavy <span class="num">(<?php echo countget(23, $id); ?>)</span></a></li>
					<li><a href="javascript:filter('Curly')"><img src="<?php echo $this->getSkinUrl('images/curly.png')?>" >Curly <span class="num">(<?php echo countget(24, $id); ?>)</span></a></li>
					<li><a href="javascript:filter('Coily')"><img src="<?php echo $this->getSkinUrl('images/coily.png')?>" >Coily <span class="num">(<?php echo countget(21, $id); ?>)</span></a></li>
				</ul>
			</div><!-- listing-tabber -->
			<div class="product-listing">
				<ul>
					<?php 
						foreach($collection as $_product){
						$_product = Mage::getModel("catalog/product")->load($_product->getId());
					?>
					<li class="item <?php echo $_product->getAttributeText("hair_type"); ?>">
						<a href="#" title="" class="product-image">
							<img id="product-collection-image-3" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(210); ?>" alt="Brazilian Kinky Curly"></a>
						<div class="product-info" style="min-height: 87px;">
							<h2 class="product-name">
							<a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $_product->getName(); ?>">
								<?php 
									$wordsCountCategory = strlen($_product->getName());
									if ($wordsCountCategory > 15) { 
									echo substr($this->htmlEscape($_product->getName()), 0, 15) . '...';
									} else {
									echo $_product->getName();
									} 
									?>							 
							</a>
							</h2>
							<h3 class="added-by">By <?php echo $sellerPage->getStoreTitle(); ?></h3>
                            <div class="size-price-wrapper">
								<div class="product-size">
									<span><?php echo round($_product->getSizeFilter(),0); ?>" inch</span>
								</div>
								<div class="price-box">                                            
									<?php if($_product->getSpecialPrice()){ ?>
										<p class="old-price"> 
										<span class="price-label">Regular Price:</span>
											<span class="price" id="old-price-3">
													<?php echo Mage::helper('core')->currency($_product->getPrice(), true, false); ?>
											</span>
										</p>
									<?php } ?>
									<p class="special-price">
										<span class="price-label">Special Price</span>
										<span class="price" id="product-price-3">
											<?php echo Mage::helper('core')->currency($_product->getSpecialPrice()? $_product->getSpecialPrice():$_product->getPrice() , true, false); ?>
										</span>
									</p>
								</div>
							</div>
						</div>
					</li>
					<?php } ?>
				</ul>
				<a class="view-more" href="javascript:filter('item')">View all</a>
			</div>
		</div>
	</div><!-- under-sink-wrapper -->
 <?php }else{ 
 
$id = $this->getRequest()->getParam('id');
$currentDate = Mage::getModel('core/date')->date('Y-m-d');

/**
 * display product collection
 */
$sellerPage = Mage::getModel('marketplace/sellerprofile')->collectprofile($id);
$collection = Mage::getModel ( 'catalog/product' )->getCollection ()->addFieldToFilter ( 'seller_id', $id);
$sellerPage = Mage::getModel('marketplace/sellerprofile')->collectprofile($id);
?>

<div class="clear"></div>
	<div class="under-sink-wrapper">
		<div class="under-sink-container">
			<h1><?php echo $this->__("Similar Bundles") ?></h1>
			<p class="title-img"><img src="http://synapse.asia/marketplace9196/skin/frontend/theme9196/default/images/heading-border.png"></p>
			
			<div class="product-listing">
				<ul>
					<?php 
						foreach($collection as $_product){
						$_product = Mage::getModel("catalog/product")->load($_product->getId());
					?>
					<li class="item <?php echo $_product->getAttributeText("hair_type"); ?>">
						<a href="<?php echo $_product->getProductUrl(); ?>" title="" class="product-image">
							<img id="product-collection-image-3" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(210); ?>" alt="Brazilian Kinky Curly"></a>
						<div class="product-info" style="min-height: 87px;">
							<h2 class="product-name">
							<a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $_product->getName(); ?>">
								<?php 
									$wordsCountCategory = strlen($_product->getName());
									if ($wordsCountCategory > 15) { 
									echo substr($this->htmlEscape($_product->getName()), 0, 15) . '...';
									} else {
									echo $_product->getName();
									} 
									?>							 
							</a>
							</h2>
							<h3 class="added-by">By <?php echo $sellerPage->getStoreTitle(); ?></h3>
                            <div class="size-price-wrapper">
								<div class="product-size">
									<span><?php echo round($_product->getSizeFilter(),0); ?>" inch</span>
								</div>
								<div class="price-box">                                            
									<?php if($_product->getSpecialPrice()){ ?>
										<p class="old-price"> 
										<span class="price-label">Regular Price:</span>
											<span class="price" id="old-price-3">
													<?php echo Mage::helper('core')->currency($_product->getPrice(), true, false); ?>
											</span>
										</p>
									<?php } ?>
									<p class="special-price">
										<span class="price-label">Special Price</span>
										<span class="price" id="product-price-3">
											<?php echo Mage::helper('core')->currency($_product->getSpecialPrice()? $_product->getSpecialPrice():$_product->getPrice() , true, false); ?>
										</span>
									</p>
								</div>
							</div>
						</div>
					</li>
					<?php } ?>
				</ul>
			</div>
		</div>
	</div><!-- get look -->
 <?php } ?>